### PR TITLE
New installer

### PR DESCRIPTION
**Pull request by slxdy**
# A new installer made in .NET 8.0 with Avalonia.
Introducing new features, including a completely redesigned UI, a game list (with an automatic Steam game detector), automatic .NET Runtime installer, support for Nightly builds, and more.

## To-do list:
- [x] Auto-generate user folders
- [x] Nightly builds toggle
- [x] Socials buttons
- [x] UI Polishing (few details, like preventing the user from closing the window during installation)
- [x] Auto-updater
- [x] Error handling (full code review)
- [x] Readme rewrite
- [x] Write new Steam reader
- [x] Fix long game name wrapping
- [x] Check for ML.dll in net6 dir
- [x] Add support for Epic Games games
- [x] Add support for GOG
- [x] Fix nightly versioning (waiting for Herp)
- [x] Final tests

### Alpha build
https://github.com/slxdy/MelonLoader.Installer/releases/tag/4.0-alpha
### Build it yourself
You can clone this branch and build with `dotnet publish` (publish isn't required, but it produces a trimmed self-contained build). You can find the output in `repo/Output/win-x64`.

### CODE REVIEW

**Comment by slxdy** [comment]
@HerpDerpinstine
Would it be a problem to relicense the installer to GPL 3.0? I'm using a Steam game finder package that's licensed under GPL 3.0, and its a big part of the project. All other dependencies use MIT.

**Comment by SamboyCoding** [comment]
Finding steam installs is not hard, I don't think it's worth worrying about a relicense for something so minor

**Comment by slxdy** [comment]
It would require a lot of extra understanding and writing. I could write my own Steam parsing tool, but it would definitely be faster and more reliable to just use the nuget (which is actively being maintained). Is relicensing really not possible?

**Comment by slxdy** [comment]
The code is a nightmare. But it works.

**Comment by slxdy** [comment]
Ready for testing. Let me know if there is any feedback or bugs I should fix.

**Pull request merged**
